<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom Resident Report</title>
    <link rel="icon" type="image/png" href="/iCensus-ent/public/assets/img/iCensusLogoOnly2.png">
    <?php if (!empty($charts)): ?>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <?php endif; ?>
    <style>
        body { font-family: sans-serif; }
        .report-container { max-width: 1000px; margin: auto; padding: 2rem; background: #fff; }
        .report-header { 
            text-align: center; 
            border-bottom: 2px solid #333; 
            margin-bottom: 2rem; 
            padding-bottom: 1rem; 
        }
        .report-header img { 
            max-width: 150px; 
            margin-bottom: 1rem; 
        }
        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .charts-section { display: flex; flex-wrap: wrap; justify-content: center; gap: 1rem; margin-top: 2rem; page-break-before: always; }
        .chart-container { width: 100%; max-width: 600px; height: 400px; page-break-inside: avoid; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <button class="no-print" onclick="window.print()" style="position:fixed; top:10px; right:10px; padding:10px;">Print</button>
    <div class="report-container">
        <div class="report-header">
            <img src="/iCensus-ent/public/assets/img/iCensusLogoSmaller.png" alt="iCensus Logo">
            <div>
                <p>Generated on: <?= date('Y-m-d H:i:s') ?></p>
                <?php if (isset($user) && isset($user['full_name'])): ?>
                    <p>Generated by: <?= htmlspecialchars($user['full_name']) ?></p>
                <?php endif; ?>
            </div>
        </div>
        
        <?php if (!empty($results) && !empty($headers)): ?>
            <section>
                <h2>Resident Data</h2>
                <table>
                    <thead>
                        <tr>
                            <?php foreach ($headers as $header): ?>
                                <th><?= htmlspecialchars($header) ?></th>
                            <?php endforeach; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($results as $row): ?>
                            <tr>
                                <?php foreach (array_keys($headers) as $col_key): ?>
                                    <td><?= htmlspecialchars($row[$col_key] ?? '') ?></td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </section>
        <?php endif; ?>
        
        <?php if (!empty($charts)): ?>
            <section class="charts-section">
                <?php foreach ($charts as $chart): ?>
                    <div id="chart_div_<?= $chart['id'] ?>" class="chart-container"></div>
                <?php endforeach; ?>
            </section>
            <script>
                google.charts.load('current', {'packages':['corechart']});
                google.charts.setOnLoadCallback(drawCharts);
                function drawCharts() {
                    <?php foreach ($charts as $chart): ?>
                        (function() {
                            const chartData = <?= json_encode($chart['data']) ?>;
                            const chartType = '<?= $chart['type'] ?>';
                            const chartTitle = '<?= addslashes($chart['title']) ?>';
                            const chartDiv = document.getElementById('chart_div_<?= $chart['id'] ?>');

                            if (chartType === 'KPI') {
                                chartDiv.innerHTML = `<div style="text-align:center; padding-top: 50px;"><h2>${chartTitle}</h2><p style="font-size: 4rem; font-weight: bold;">${chartData.value || 0}</p></div>`;
                                return;
                            }

                            const dataTable = new google.visualization.DataTable();
                            dataTable.addColumn('string', 'Category');
                            dataTable.addColumn('number', 'Value');
                            
                            // --- START: MODIFICATION ---
                            // This now creates labels that include the value, e.g., "Male (15)"
                            const rows = Object.entries(chartData).map(([key, value]) => [`${key} (${value})`, value]);
                            // --- END: MODIFICATION ---

                            dataTable.addRows(rows);

                            const options = { 
                                title: chartTitle,
                                width: '100%',
                                height: '100%',
                                chartArea: { width: '80%', height: '70%' },
                                legend: { position: 'bottom' }
                            };

                            let chartInstance;
                            if (chartType === 'BarChart') {
                                chartInstance = new google.visualization.BarChart(chartDiv);
                            } else if (chartType === 'ColumnChart') {
                                chartInstance = new google.visualization.ColumnChart(chartDiv);
                            } else {
                                if (chartType === 'DonutChart') {
                                    options.pieHole = 0.4;
                                }
                                chartInstance = new google.visualization.PieChart(chartDiv);
                            }
                            chartInstance.draw(dataTable, options);
                        })();
                    <?php endforeach; ?>
                }
            </script>
        <?php endif; ?>
    </div>
</body>
</html>